language: python
sudo: required
dist: trusty
python:
  - '2.7'
  - '3.6'
  - '3.7'
cache: pip
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - sudo apt-get install build-essential python-dev libxml2 libxml2-dev zlib1g-dev
  - conda update --yes conda
  - conda install --yes python="$TRAVIS_PYTHON_VERSION" numpy scipy networkx nose pandas jinja2 plotly pycairo
  - mkdir -p ~/.config/matplotlib
  - echo "backend:Agg" > ~/.config/matplotlib/matplotlibrc
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install python-igraph
  - pip install nose-exclude
  - pip install nose-timer
  - pip install codecov

install:
  - sudo apt-get install graphviz
  - python setup.py build --build-lib=build/lib

script:
  - python copy_sample_data.py
  - travis_wait 45 nosetests build/lib/magine/tests --with-coverage --cover-inclusive --cover-package=build/lib/magine --logging-level=INFO --with-timer
after_success:
  - codecov
  - coveralls
