language: python
sudo: required
dist: trusty
env:
- PYVER=2.7
- PYVER=3.6
- PYVER=3.7
cache: pip
before_install:
  # setup igraph.
  - sudo apt-get install build-essential python-dev libxml2 libxml2-dev zlib1g-dev autoconf
  - git clone https://github.com/igraph/igraph.git
  - cd igraph
  - autoconf
  - ./configure
  - make
  - make check
  - make install
  - cd ..
  # install conda
  - wget http://repo.continuum.io/miniconda/Miniconda${PYVER:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  - conda update --yes conda
  - conda install --yes python="$PYVER" numpy scipy networkx nose pandas jinja2 plotly pycairo
  - pip install python-igraph
  - mkdir -p ~/.config/matplotlib
  - echo "backend:Agg" > ~/.config/matplotlib/matplotlibrc
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose-exclude
  - pip install nose-timer
  - pip install codecov

install:
  - sudo apt-get install graphviz
  - python setup.py build --build-lib=build/lib

script:
  - python copy_sample_data.py
  - travis_wait 45 nosetests build/lib/magine/tests --with-coverage --cover-inclusive --cover-package=build/lib/magine --logging-level=INFO --with-timer
after_success:
  - codecov
  - coveralls
